// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An [attestor][google.cloud.binaryauthorization.v1.Attestor] that attests to
/// container image artifacts. An existing attestor cannot be modified except
/// where indicated.
///
/// [google.cloud.binaryauthorization.v1.Attestor]: <doc:Attestor>
public struct Attestor: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name, in the format:
  /// `projects/*/attestors/*`. This field may not be updated.
  public var name: Swift.String = Swift.String()

  /// Optional. A descriptive comment.  This field may be updated.
  /// The field may be displayed in chooser dialogs.
  public var description: Swift.String = Swift.String()

  /// Output only. Time when the attestor was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. A checksum, returned by the server, that can be sent on update
  /// requests to ensure the attestor has an up-to-date value before attempting
  /// to update it. See https://google.aip.dev/154.
  public var etag: Swift.String = Swift.String()

  public var attestorType: AttestorTypeOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Attestor`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Attestor().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let userOwnedGrafeasNote = CodingKeys(stringValue: "userOwnedGrafeasNote")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let etag = CodingKeys(stringValue: "etag")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "description",
      "userOwnedGrafeasNote",
      "updateTime",
      "etag",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }

    var attestorType: AttestorTypeOneOf? = nil
    let attestorTypeCheckAndSet = {
      if attestorType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'attestorType'"))
      }
      attestorType = $0
    }
    if let userOwnedGrafeasNote = try container.decodeIfPresent(
      UserOwnedGrafeasNote.self, forKey: .userOwnedGrafeasNote)
    {
      try attestorTypeCheckAndSet(.userOwnedGrafeasNote(userOwnedGrafeasNote))
    }
    self.attestorType = attestorType
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.etag, forKey: .etag)

    if let choice = self.attestorType {
      switch choice {
      case .userOwnedGrafeasNote(let value):
        try container.encode(value, forKey: .userOwnedGrafeasNote)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum AttestorTypeOneOf: Codable, Equatable, Sendable {
    /// This specifies how an attestation will be read, and how it will be used
    /// during policy enforcement.
    indirect case userOwnedGrafeasNote(UserOwnedGrafeasNote)
  }

  /// The type URL for `Attestor`: `"type.googleapis.com/google.cloud.binaryauthorization.v1.Attestor"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.binaryauthorization.v1.Attestor"
  }

  /// Initialize an instance of `Attestor` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.binaryauthorization.v1.Attestor"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `Attestor` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
