// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An [attestor public
/// key][google.cloud.binaryauthorization.v1.AttestorPublicKey] that will be used
/// to verify attestations signed by this attestor.
///
/// [google.cloud.binaryauthorization.v1.AttestorPublicKey]: <doc:AttestorPublicKey>
public struct AttestorPublicKey: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. A descriptive comment. This field may be updated.
  public var comment: Swift.String = Swift.String()

  /// The ID of this public key.
  /// Signatures verified by Binary Authorization must include the ID of the
  /// public key that can be used to verify them, and that ID must match the
  /// contents of this field exactly. Additional restrictions on this field can
  /// be imposed based on which public key type is encapsulated. See the
  /// documentation on `public_key` cases below for details.
  public var id: Swift.String = Swift.String()

  public var publicKey: PublicKeyOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AttestorPublicKey`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AttestorPublicKey().with { $0.comment = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let comment = CodingKeys(stringValue: "comment")
    static let id = CodingKeys(stringValue: "id")
    static let asciiArmoredPgpPublicKey = CodingKeys(stringValue: "asciiArmoredPgpPublicKey")
    static let pkixPublicKey = CodingKeys(stringValue: "pkixPublicKey")

    static let _knownKeys: Set<Swift.String> = [
      "comment",
      "id",
      "asciiArmoredPgpPublicKey",
      "pkixPublicKey",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .comment) {
      self.comment = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
      self.id = value
    }

    var publicKey: PublicKeyOneOf? = nil
    let publicKeyCheckAndSet = {
      if publicKey != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'publicKey'"))
      }
      publicKey = $0
    }
    if let asciiArmoredPgpPublicKey = try container.decodeIfPresent(
      Swift.String.self, forKey: .asciiArmoredPgpPublicKey)
    {
      try publicKeyCheckAndSet(.asciiArmoredPgpPublicKey(asciiArmoredPgpPublicKey))
    }
    if let pkixPublicKey = try container.decodeIfPresent(PkixPublicKey.self, forKey: .pkixPublicKey)
    {
      try publicKeyCheckAndSet(.pkixPublicKey(pkixPublicKey))
    }
    self.publicKey = publicKey
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.comment, forKey: .comment)
    try container.encode(self.id, forKey: .id)

    if let choice = self.publicKey {
      switch choice {
      case .asciiArmoredPgpPublicKey(let value):
        try container.encode(value, forKey: .asciiArmoredPgpPublicKey)
      case .pkixPublicKey(let value):
        try container.encode(value, forKey: .pkixPublicKey)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum PublicKeyOneOf: Codable, Equatable, Sendable {
    /// ASCII-armored representation of a PGP public key, as the entire output by
    /// the command `gpg --export --armor foo@example.com` (either LF or CRLF
    /// line endings).
    /// When using this field, `id` should be left blank.  The Binary
    /// Authorization API handlers will calculate the ID and fill it in
    /// automatically.  Binary Authorization computes this ID as the OpenPGP
    /// RFC4880 V4 fingerprint, represented as upper-case hex.  If `id` is
    /// provided by the caller, it will be overwritten by the API-calculated ID.
    case asciiArmoredPgpPublicKey(Swift.String)
    /// A raw PKIX SubjectPublicKeyInfo format public key.
    ///
    /// NOTE: `id` may be explicitly provided by the caller when using this
    /// type of public key, but it MUST be a valid RFC3986 URI. If `id` is left
    /// blank, a default one will be computed based on the digest of the DER
    /// encoding of the public key.
    indirect case pkixPublicKey(PkixPublicKey)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.binaryauthorization.v1.AttestorPublicKey"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
