// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for
/// [BinauthzManagementServiceV1.CreateAttestor][google.cloud.binaryauthorization.v1.BinauthzManagementServiceV1.CreateAttestor].
///
/// [google.cloud.binaryauthorization.v1.BinauthzManagementServiceV1.CreateAttestor]: <doc:BinauthzManagementServiceV1Client/createAttestor(request:options:)>
public struct CreateAttestorRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The parent of this
  /// [attestor][google.cloud.binaryauthorization.v1.Attestor].
  ///
  /// [google.cloud.binaryauthorization.v1.Attestor]: <doc:Attestor>
  public var parent: Swift.String = Swift.String()

  /// Required. The [attestors][google.cloud.binaryauthorization.v1.Attestor] ID.
  ///
  /// [google.cloud.binaryauthorization.v1.Attestor]: <doc:Attestor>
  public var attestorId: Swift.String = Swift.String()

  /// Required. The initial
  /// [attestor][google.cloud.binaryauthorization.v1.Attestor] value. The service
  /// will overwrite the [attestor
  /// name][google.cloud.binaryauthorization.v1.Attestor.name] field with the
  /// resource name, in the format `projects/*/attestors/*`.
  ///
  /// [google.cloud.binaryauthorization.v1.Attestor]: <doc:Attestor>
  /// [google.cloud.binaryauthorization.v1.Attestor.name]: <doc:Attestor/name>
  public var attestor: Attestor? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateAttestorRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateAttestorRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let attestorId = CodingKeys(stringValue: "attestorId")
    static let attestor = CodingKeys(stringValue: "attestor")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "attestorId",
      "attestor",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .attestorId) {
      self.attestorId = value
    }
    self.attestor = try container.decodeIfPresent(Attestor.self, forKey: .attestor)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.attestorId, forKey: .attestorId)
    try container.encodeIfPresent(self.attestor, forKey: .attestor)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `CreateAttestorRequest`: `"type.googleapis.com/google.cloud.binaryauthorization.v1.CreateAttestorRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.binaryauthorization.v1.CreateAttestorRequest"
  }

  /// Initialize an instance of `CreateAttestorRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.binaryauthorization.v1.CreateAttestorRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `CreateAttestorRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
