// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A public key in the PkixPublicKey
/// [format](https://tools.ietf.org/html/rfc5280#section-4.1.2.7). Public keys of
/// this type are typically textually encoded using the PEM format.
public struct PkixPublicKey: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A PEM-encoded public key, as described in
  /// https://tools.ietf.org/html/rfc7468#section-13
  public var publicKeyPem: Swift.String = Swift.String()

  /// The signature algorithm used to verify a message against a signature using
  /// this key.
  /// These signature algorithm must match the structure and any object
  /// identifiers encoded in `public_key_pem` (i.e. this algorithm must match
  /// that of the public key).
  public var signatureAlgorithm: PkixPublicKey.SignatureAlgorithm =
    PkixPublicKey.SignatureAlgorithm()

  /// Optional. The ID of this public key.
  /// Signatures verified by Binary Authorization must include the ID of the
  /// public key that can be used to verify them. The ID must match exactly
  /// contents of the `key_id` field exactly.
  ///
  /// The ID may be explicitly provided by the caller, but it MUST be a valid
  /// RFC3986 URI. If `key_id` is left blank and this `PkixPublicKey` is not used
  /// in the context of a wrapper (see next paragraph), a default key ID will be
  /// computed based on the digest of the DER encoding of the public key.
  ///
  /// If this `PkixPublicKey` is used in the context of a wrapper that has its
  /// own notion of key ID (e.g. `AttestorPublicKey`), then this field can
  /// either match that value exactly, or be left blank, in which case it behaves
  /// exactly as though it is equal to that wrapper value.
  public var keyId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PkixPublicKey`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PkixPublicKey().with { $0.publicKeyPem = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let publicKeyPem = CodingKeys(stringValue: "publicKeyPem")
    static let signatureAlgorithm = CodingKeys(stringValue: "signatureAlgorithm")
    static let keyId = CodingKeys(stringValue: "keyId")

    static let _knownKeys: Set<Swift.String> = [
      "publicKeyPem",
      "signatureAlgorithm",
      "keyId",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .publicKeyPem) {
      self.publicKeyPem = value
    }
    if let value = try container.decodeIfPresent(
      PkixPublicKey.SignatureAlgorithm.self, forKey: .signatureAlgorithm)
    {
      self.signatureAlgorithm = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .keyId) {
      self.keyId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.publicKeyPem, forKey: .publicKeyPem)
    try container.encode(self.signatureAlgorithm, forKey: .signatureAlgorithm)
    try container.encode(self.keyId, forKey: .keyId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Represents a signature algorithm and other information necessary to verify
  /// signatures with a given public key.
  /// This is based primarily on the public key types supported by Tink's
  /// PemKeyType, which is in turn based on KMS's supported signing
  /// [algorithms](https://cloud.google.com/kms/docs/algorithms). In the future,
  /// Binary Authorization might support additional public key types
  /// independently of Tink and/or KMS.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum SignatureAlgorithm: Codable, Equatable, Hashable, Sendable {
    /// Not specified.
    case unspecified
    /// RSASSA-PSS 2048 bit key with a SHA256 digest.
    case rsaPss2048Sha256
    /// RSASSA-PSS 3072 bit key with a SHA256 digest.
    case rsaPss3072Sha256
    /// RSASSA-PSS 4096 bit key with a SHA256 digest.
    case rsaPss4096Sha256
    /// RSASSA-PSS 4096 bit key with a SHA512 digest.
    case rsaPss4096Sha512
    /// RSASSA-PKCS1-v1_5 with a 2048 bit key and a SHA256 digest.
    case rsaSignPkcs12048Sha256
    /// RSASSA-PKCS1-v1_5 with a 3072 bit key and a SHA256 digest.
    case rsaSignPkcs13072Sha256
    /// RSASSA-PKCS1-v1_5 with a 4096 bit key and a SHA256 digest.
    case rsaSignPkcs14096Sha256
    /// RSASSA-PKCS1-v1_5 with a 4096 bit key and a SHA512 digest.
    case rsaSignPkcs14096Sha512
    /// ECDSA on the NIST P-256 curve with a SHA256 digest.
    case ecdsaP256Sha256
    /// ECDSA on the NIST P-384 curve with a SHA384 digest.
    case ecdsaP384Sha384
    /// ECDSA on the NIST P-521 curve with a SHA512 digest.
    case ecdsaP521Sha512
    /// ML-DSA-65 Post-Quantum Cryptography signature algorithm.
    case mlDsa65
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .rsaPss2048Sha256: return 1
      case .rsaPss3072Sha256: return 2
      case .rsaPss4096Sha256: return 3
      case .rsaPss4096Sha512: return 4
      case .rsaSignPkcs12048Sha256: return 5
      case .rsaSignPkcs13072Sha256: return 6
      case .rsaSignPkcs14096Sha256: return 7
      case .rsaSignPkcs14096Sha512: return 8
      case .ecdsaP256Sha256: return 9
      case .ecdsaP384Sha384: return 10
      case .ecdsaP521Sha512: return 11
      case .mlDsa65: return 13
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SIGNATURE_ALGORITHM_UNSPECIFIED"
      case .rsaPss2048Sha256: return "RSA_PSS_2048_SHA256"
      case .rsaPss3072Sha256: return "RSA_PSS_3072_SHA256"
      case .rsaPss4096Sha256: return "RSA_PSS_4096_SHA256"
      case .rsaPss4096Sha512: return "RSA_PSS_4096_SHA512"
      case .rsaSignPkcs12048Sha256: return "RSA_SIGN_PKCS1_2048_SHA256"
      case .rsaSignPkcs13072Sha256: return "RSA_SIGN_PKCS1_3072_SHA256"
      case .rsaSignPkcs14096Sha256: return "RSA_SIGN_PKCS1_4096_SHA256"
      case .rsaSignPkcs14096Sha512: return "RSA_SIGN_PKCS1_4096_SHA512"
      case .ecdsaP256Sha256: return "ECDSA_P256_SHA256"
      case .ecdsaP384Sha384: return "ECDSA_P384_SHA384"
      case .ecdsaP521Sha512: return "ECDSA_P521_SHA512"
      case .mlDsa65: return "ML_DSA_65"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SignatureAlgorithm/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SIGNATURE_ALGORITHM_UNSPECIFIED": self = .unspecified
      case "RSA_PSS_2048_SHA256": self = .rsaPss2048Sha256
      case "RSA_SIGN_PSS_2048_SHA256": self = .rsaPss2048Sha256
      case "RSA_PSS_3072_SHA256": self = .rsaPss3072Sha256
      case "RSA_SIGN_PSS_3072_SHA256": self = .rsaPss3072Sha256
      case "RSA_PSS_4096_SHA256": self = .rsaPss4096Sha256
      case "RSA_SIGN_PSS_4096_SHA256": self = .rsaPss4096Sha256
      case "RSA_PSS_4096_SHA512": self = .rsaPss4096Sha512
      case "RSA_SIGN_PSS_4096_SHA512": self = .rsaPss4096Sha512
      case "RSA_SIGN_PKCS1_2048_SHA256": self = .rsaSignPkcs12048Sha256
      case "RSA_SIGN_PKCS1_3072_SHA256": self = .rsaSignPkcs13072Sha256
      case "RSA_SIGN_PKCS1_4096_SHA256": self = .rsaSignPkcs14096Sha256
      case "RSA_SIGN_PKCS1_4096_SHA512": self = .rsaSignPkcs14096Sha512
      case "ECDSA_P256_SHA256": self = .ecdsaP256Sha256
      case "EC_SIGN_P256_SHA256": self = .ecdsaP256Sha256
      case "ECDSA_P384_SHA384": self = .ecdsaP384Sha384
      case "EC_SIGN_P384_SHA384": self = .ecdsaP384Sha384
      case "ECDSA_P521_SHA512": self = .ecdsaP521Sha512
      case "EC_SIGN_P521_SHA512": self = .ecdsaP521Sha512
      case "ML_DSA_65": self = .mlDsa65
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SignatureAlgorithm/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .rsaPss2048Sha256
      case 2: self = .rsaPss3072Sha256
      case 3: self = .rsaPss4096Sha256
      case 4: self = .rsaPss4096Sha512
      case 5: self = .rsaSignPkcs12048Sha256
      case 6: self = .rsaSignPkcs13072Sha256
      case 7: self = .rsaSignPkcs14096Sha256
      case 8: self = .rsaSignPkcs14096Sha512
      case 9: self = .ecdsaP256Sha256
      case 10: self = .ecdsaP384Sha384
      case 11: self = .ecdsaP521Sha512
      case 13: self = .mlDsa65
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SIGNATURE_ALGORITHM_UNSPECIFIED")
      case .rsaPss2048Sha256: return try container.encode("RSA_PSS_2048_SHA256")
      case .rsaPss3072Sha256: return try container.encode("RSA_PSS_3072_SHA256")
      case .rsaPss4096Sha256: return try container.encode("RSA_PSS_4096_SHA256")
      case .rsaPss4096Sha512: return try container.encode("RSA_PSS_4096_SHA512")
      case .rsaSignPkcs12048Sha256: return try container.encode("RSA_SIGN_PKCS1_2048_SHA256")
      case .rsaSignPkcs13072Sha256: return try container.encode("RSA_SIGN_PKCS1_3072_SHA256")
      case .rsaSignPkcs14096Sha256: return try container.encode("RSA_SIGN_PKCS1_4096_SHA256")
      case .rsaSignPkcs14096Sha512: return try container.encode("RSA_SIGN_PKCS1_4096_SHA512")
      case .ecdsaP256Sha256: return try container.encode("ECDSA_P256_SHA256")
      case .ecdsaP384Sha384: return try container.encode("ECDSA_P384_SHA384")
      case .ecdsaP521Sha512: return try container.encode("ECDSA_P521_SHA512")
      case .mlDsa65: return try container.encode("ML_DSA_65")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.binaryauthorization.v1.PkixPublicKey"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
