// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for
/// [BinauthzManagementServiceV1.UpdatePolicy][google.cloud.binaryauthorization.v1.BinauthzManagementServiceV1.UpdatePolicy].
///
/// [google.cloud.binaryauthorization.v1.BinauthzManagementServiceV1.UpdatePolicy]: <doc:BinauthzManagementServiceV1Client/updatePolicy(request:options:)>
public struct UpdatePolicyRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. A new or updated
  /// [policy][google.cloud.binaryauthorization.v1.Policy] value. The service
  /// will overwrite the [policy
  /// name][google.cloud.binaryauthorization.v1.Policy.name] field with the
  /// resource name in the request URL, in the format `projects/*/policy`.
  ///
  /// [google.cloud.binaryauthorization.v1.Policy]: <doc:Policy>
  /// [google.cloud.binaryauthorization.v1.Policy.name]: <doc:Policy/name>
  public var policy: GoogleCloudBinaryAuthorizationV1.Policy? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpdatePolicyRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdatePolicyRequest().with { $0.policy = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let policy = CodingKeys(stringValue: "policy")

    static let _knownKeys: Set<Swift.String> = [
      "policy"
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.policy = try container.decodeIfPresent(
      GoogleCloudBinaryAuthorizationV1.Policy.self, forKey: .policy)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.policy, forKey: .policy)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `UpdatePolicyRequest`: `"type.googleapis.com/google.cloud.binaryauthorization.v1.UpdatePolicyRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.binaryauthorization.v1.UpdatePolicyRequest"
  }

  /// Initialize an instance of `UpdatePolicyRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.binaryauthorization.v1.UpdatePolicyRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `UpdatePolicyRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
