// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An [user owned Grafeas
/// note][google.cloud.binaryauthorization.v1.UserOwnedGrafeasNote] references a
/// Grafeas Attestation.Authority Note created by the user.
///
/// [google.cloud.binaryauthorization.v1.UserOwnedGrafeasNote]: <doc:UserOwnedGrafeasNote>
public struct UserOwnedGrafeasNote: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The Grafeas resource name of a Attestation.Authority Note,
  /// created by the user, in the format: `projects/[PROJECT_ID]/notes/*`. This
  /// field may not be updated. A project ID must be used, not a project number.
  ///
  /// An attestation by this attestor is stored as a Grafeas
  /// Attestation.Authority Occurrence that names a container image and that
  /// links to this Note. Grafeas is an external dependency.
  public var noteReference: Swift.String = Swift.String()

  /// Optional. Public keys that verify attestations signed by this
  /// attestor.  This field may be updated.
  ///
  /// If this field is non-empty, one of the specified public keys must
  /// verify that an attestation was signed by this attestor for the
  /// image specified in the admission request.
  ///
  /// If this field is empty, this attestor always returns that no
  /// valid attestations exist.
  public var publicKeys: [AttestorPublicKey] = []

  /// Output only. This field will contain the service account email address
  /// that this attestor will use as the principal when querying Container
  /// Analysis. Attestor administrators must grant this service account the
  /// IAM role needed to read attestations from the
  /// [note_reference][google.cloud.binaryauthorization.v1.UserOwnedGrafeasNote.note_reference]
  /// in Container Analysis (`containeranalysis.notes.occurrences.viewer`).
  ///
  /// This email address is fixed for the lifetime of the attestor, but callers
  /// should not make any other assumptions about the service account email;
  /// future versions may use an email based on a different naming pattern.
  ///
  /// [google.cloud.binaryauthorization.v1.UserOwnedGrafeasNote.note_reference]: <doc:UserOwnedGrafeasNote/noteReference>
  public var delegationServiceAccountEmail: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UserOwnedGrafeasNote`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UserOwnedGrafeasNote().with { $0.noteReference = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let noteReference = CodingKeys(stringValue: "noteReference")
    static let publicKeys = CodingKeys(stringValue: "publicKeys")
    static let delegationServiceAccountEmail = CodingKeys(
      stringValue: "delegationServiceAccountEmail")

    static let _knownKeys: Set<Swift.String> = [
      "noteReference",
      "publicKeys",
      "delegationServiceAccountEmail",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .noteReference) {
      self.noteReference = value
    }
    if let value = try container.decodeIfPresent([AttestorPublicKey].self, forKey: .publicKeys) {
      self.publicKeys = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .delegationServiceAccountEmail)
    {
      self.delegationServiceAccountEmail = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.noteReference, forKey: .noteReference)
    try container.encode(self.publicKeys, forKey: .publicKeys)
    try container.encode(self.delegationServiceAccountEmail, forKey: .delegationServiceAccountEmail)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.binaryauthorization.v1.UserOwnedGrafeasNote"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
