// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleGrafeasV1
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for
/// [ValidationHelperV1.ValidateAttestationOccurrence][google.cloud.binaryauthorization.v1.ValidationHelperV1.ValidateAttestationOccurrence].
///
/// [google.cloud.binaryauthorization.v1.ValidationHelperV1.ValidateAttestationOccurrence]: <doc:ValidationHelperV1Client/validateAttestationOccurrence(request:options:)>
public struct ValidateAttestationOccurrenceRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the
  /// [Attestor][google.cloud.binaryauthorization.v1.Attestor] of the
  /// [occurrence][grafeas.v1.Occurrence], in the format
  /// `projects/*/attestors/*`.
  ///
  /// [google.cloud.binaryauthorization.v1.Attestor]: <doc:Attestor>
  public var attestor: Swift.String = Swift.String()

  /// Required. An [AttestationOccurrence][grafeas.v1.AttestationOccurrence] to
  /// be checked that it can be verified by the `Attestor`. It does not have to
  /// be an existing entity in Container Analysis. It must otherwise be a valid
  /// `AttestationOccurrence`.
  ///
  /// [grafeas.v1.AttestationOccurrence]: https://www.google.com/search?q=Swift+grafeas.v1+GoogleGrafeasV1.AttestationOccurrence
  public var attestation: GoogleGrafeasV1.AttestationOccurrence? = nil

  /// Required. The resource name of the [Note][grafeas.v1.Note] to which the
  /// containing [Occurrence][grafeas.v1.Occurrence] is associated.
  public var occurrenceNote: Swift.String = Swift.String()

  /// Required. The URI of the artifact (e.g. container image) that is the
  /// subject of the containing [Occurrence][grafeas.v1.Occurrence].
  public var occurrenceResourceUri: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ValidateAttestationOccurrenceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ValidateAttestationOccurrenceRequest().with { $0.attestor = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let attestor = CodingKeys(stringValue: "attestor")
    static let attestation = CodingKeys(stringValue: "attestation")
    static let occurrenceNote = CodingKeys(stringValue: "occurrenceNote")
    static let occurrenceResourceUri = CodingKeys(stringValue: "occurrenceResourceUri")

    static let _knownKeys: Set<Swift.String> = [
      "attestor",
      "attestation",
      "occurrenceNote",
      "occurrenceResourceUri",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .attestor) {
      self.attestor = value
    }
    self.attestation = try container.decodeIfPresent(
      GoogleGrafeasV1.AttestationOccurrence.self, forKey: .attestation)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .occurrenceNote) {
      self.occurrenceNote = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .occurrenceResourceUri)
    {
      self.occurrenceResourceUri = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.attestor, forKey: .attestor)
    try container.encodeIfPresent(self.attestation, forKey: .attestation)
    try container.encode(self.occurrenceNote, forKey: .occurrenceNote)
    try container.encode(self.occurrenceResourceUri, forKey: .occurrenceResourceUri)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ValidateAttestationOccurrenceRequest`: `"type.googleapis.com/google.cloud.binaryauthorization.v1.ValidateAttestationOccurrenceRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.binaryauthorization.v1.ValidateAttestationOccurrenceRequest"
  }

  /// Initialize an instance of `ValidateAttestationOccurrenceRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.binaryauthorization.v1.ValidateAttestationOccurrenceRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ValidateAttestationOccurrenceRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
